apiVersion: v1
kind: Service
metadata:
  name: mycode-server-service
  namespace: hs
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - port: 3000
      targetPort: 3000
    - port: 3001
      targetPort: 3001
    - port: 3002
      targetPort: 3002
    - port: 3003
      targetPort: 3003
    - port: 3004
      targetPort: 3004
    - port: 3005
      targetPort: 3005
