apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mycode-pvc-dynamic
  namespace: hs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
