apiVersion: v1
kind: Service
metadata:
  name: mycode-server-service
  namespace: hs
  labels:
    app: mycode-server
spec:
  selector:
    app: mycode-server
  ports:
    - protocol: TCP
      name: main
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: test
      port: 3000
      targetPort: 3000
    - protocol: TCP
      name: test2
      port: 3001
      targetPort: 3001
